<a href="https://colab.research.google.com/github/simsang1l/python_workshop/blob/main/2023summer/Day1/02_Numpy%20/ls05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 05: numpy 공부 1단계 ~ 2단계

최규빈  
2023-07-24

<a href="https://colab.research.google.com/simsang1l/python_workshop/blob/main/2023summer/Day1/02_Numpy/ls05.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" style="text-align: left"></a>

# import

In [3]:
import numpy as np

# 넘파이 공부 1단계

## 선언

In [ ]:
a=np.array([1,2,3]) # list를 만들고 ndarray화 시킴
l=[1,2,3]

#### 기본연산 브로드캐스팅

In [ ]:
a+1 ## [1,2,3] + 1 = [2,3,4]

In [ ]:
l+1

In [ ]:
a*2

In [ ]:
l*2

In [ ]:
a/2

In [ ]:
l/2

In [ ]:
a**2

In [ ]:
l**2

In [ ]:
a%2 # %2 = 2로 나눈 나머지를 리턴 a=[1,2,3]

In [ ]:
l%2

## 기타수학연산지원

In [ ]:
np.sqrt(a), np.sqrt(l)

In [ ]:
np.log(a), np.log(l)

In [ ]:
np.exp(a), np.exp(l)

In [ ]:
np.sin(a), np.sin(l)

# 넘파이 공부 2단계

## 인덱싱 1차원

`-` 선언

In [ ]:
l=[11,22,33,44,55,66]
a=np.array(l)

`-` 인덱스로 접근

In [ ]:
l[0],l[1],l[2],l[3],l[-2],l[-1]

In [ ]:
a[0],a[1],a[2],a[3],a[-2],a[-1]

`-` `:` 이용 (슬라이싱)

In [ ]:
l[2:4] # index 2에서 시작, index 4는 포함하지 않음

In [ ]:
a[2:4]

`-` 정수배열에 의한 인덱싱

In [ ]:
a

In [ ]:
a[[0,2,4]] # index=0, index=2, index=4 에 해당하는 원소를 뽑고 싶다

In [ ]:
l[[0,2,4]] # 리스트는 불가능

`-` 부울값에 의한 인덱싱

In [ ]:
a

In [ ]:
a[[True,False,True,False,True,False]]

응용하면?

In [ ]:
a < 33

In [ ]:
a[a<33]

리스트는 불가능

In [ ]:
l<33 # 여기에서부터 불가능

In [ ]:
l[[True,False,True,False,True,False]] # 이것도 불가능

## 인덱싱 2차원

`-` 중첩리스트와 2차원 np.array 선언

In [ ]:
A = [[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8],[-5,-6,-7,-8]]
A2 = np.array(A)

In [ ]:
A2

In [ ]:
A

`-` A의 원소 인덱싱

In [ ]:
A[0][0] # (1,1)의 원소

In [ ]:
A[1][2] # (2,3)의 원소

In [ ]:
A[-1][0] # (4,1)의 원소

`-` A2의 원소 인덱싱

In [ ]:
A2[0][0] # (1,1)의 원소

In [ ]:
A2[1][2] # (2,3)의 원소

In [ ]:
A2[-1][0] # (4,1)의 원소

`-` A2에서만 되는 기술 (넘파이에서 제시하는 신기술, R에서는 기본적으로
쓰던것, 이중list는 불가능)

In [ ]:
A2[0,0] # (1,1)의 원소

In [ ]:
A2[1,2] # (2,3)의 원소

In [ ]:
A2[-1,0] # (4,1)의 원소

`-` 정수배열에 의한 인덱싱 & 슬라이싱!

In [ ]:
A2

In [ ]:
A2[0,0:2] # 1행1열, 1행2열

In [ ]:
A2[0,:] # 1행

In [ ]:
A2[0] # 1행

In [ ]:
A2[[0,2],:] # 1행, 3행

In [ ]:
A2[[0,2]] # 1행, 3행

In [ ]:
A2[:,0] # 1열

In [ ]:
A2[:,[0]] # 1열

In [ ]:
A2[:,[0,2]] # 1열, 3열

In [ ]:
A2[0:2,[0,2]] # 1행~2행 //  1열,3열

## 1차원 배열의 선언

`-` 리스트나 튜플을 선언하고 형변환

In [ ]:
np.array((1,2,3)) # 튜플->넘파이어레이

In [ ]:
np.array([1,2,3]) # 리스트 ->넘파이어레이

`-` range()를 이용해서 선언하고 형변환

In [ ]:
np.array(range(10)) # range(10) -> 넘파이어레이

`-` np.zeros, np.ones

In [ ]:
np.zeros(3)

In [ ]:
np.ones(4)

`-` np.linspace

In [ ]:
np.linspace(0,1,12) # 0에서 시작하고 1에서 끝남 (양끝점 모두 포함)

In [ ]:
len(np.linspace(0,1,12)) # 길이는 12

`-` np.arange

In [ ]:
np.arange(5) # np.array(range(5))

In [ ]:
np.arange(1,6) # np.array(range(1,6))

## reshape

`-` reshape: ndarray의 특수한 기능

In [ ]:
a=np.array([11,22,33,44,55,66])
a ## 길이가 6인 벡터

In [ ]:
a.reshape(2,3) ## (2,3) matrix 라고 생각해도 무방

note: reshape은 a자체를 변화시키는것은 아님

In [ ]:
a # a는 그대로 있음

In [ ]:
b= a.reshape(2,3) # a를 reshape한 결과를 b에 저장
b

In [ ]:
a # a는 여전히 그대로 있음

`-` 다시 b를 a처럼 바꾸고 싶다

In [ ]:
b

In [ ]:
b.reshape(6) # b는 (2,3) matrix , 그런데 이것을 길이가 6인 벡터로 만들고 싶다.

`-` reshape with -1

In [ ]:
a=np.arange(24) # np.array(range(24))
a

In [ ]:
a.reshape(2,-1)

In [ ]:
a.reshape(3,-1)

In [ ]:
a.reshape(4,-1)

In [ ]:
a.reshape(5,-1)

In [ ]:
a.reshape(6,-1)

In [ ]:
a.reshape(7,-1)

In [ ]:
a.reshape(8,-1)

In [ ]:
a.reshape(12,-1)

In [ ]:
b= a.reshape(12,-1)
b

In [ ]:
b.reshape(-1) # b를 다시 길이가 24인 벡터로!

## 2차원 배열의 선언

In [ ]:
np.zeros((3,3))

In [ ]:
np.ones((3,3))

In [ ]:
np.eye(3)

In [ ]:
np.diag([1,2,3,-1])

## 랜덤으로 배열 생성

In [ ]:
np.random.randn(10) # 표쥰정규분포에서 10개를 뽑음

In [ ]:
np.random.rand(10) # 0~1사이에서 10개를 뽑음

In [ ]:
np.random.randn(4).reshape(2,2) # 표준정규분포에서 4개를 뽑고 (2,2) ndarray로 형태변환

In [ ]:
np.random.rand(4).reshape(2,2) # 0~1 4개를 뽑고 (2,2) ndarray로 형태변환

## 행렬관련기능

In [ ]:
A=np.arange(4).reshape(2,2)
A

In [ ]:
A.T # .T는 전치행렬을 구해줌

In [ ]:
np.linalg.inv(A) # np.linalg.inv는 역행렬을 구해주는 함수

In [ ]:
A @ np.linalg.inv(A) # @는 행렬곱을 수행

## 차원

`-` 넘파이배열의 차원은 .shape 으로 확인가능

`-` 아래는 모두 미묘하게 다르다.

In [ ]:
a=np.array(3.14) # 스칼라, 0d array
a, a.shape

In [ ]:
a=np.array([3.14]) # 벡터, 1d array
a, a.shape

In [ ]:
a=np.array([[3.14]]) # 매트릭스, 2d array
a, a.shape

In [ ]:
a=np.array([[[3.14]]]) # 텐서, 3d array
a, a.shape

# Quiz

`1`. shape이 ()인 numpy array를 만들어라. (즉 차원이 0인 np.array를
만들어라)

In [2]:
a= np.array(0)
a.shape

()

`2` a의 모든 원소에 1을 더하는 코드를 작성하라. (numpy를 이용할것)

``` python
a=[1,3,2,5,-3,3,8,2,3,1]
```

In [5]:
a=[1,3,2,5,-3,3,8,2,3,1]
np.array(a) + 1

array([ 2,  4,  3,  6, -2,  4,  9,  3,  4,  2])

`3` 아래와 같은 수열을 생생성하라.

    0,1,2,3,4,5,...,99

위의 수열에서 1,4,7,10,13,… 번째의 원소를 뽑아서 아래와 같은 수열을
만들어라. (첫번째 원소는 0이다)

    0,3,6,9,12,...,93,96,99

In [5]:
x = np.array(range(100))
x

x[::3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

`4`. shape이 (5,5)인 단위행렬을 만들어라.

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

`5`. numpy를 이용하여 아래의 역행렬을 구하라.

$$\begin{bmatrix}
1&  0 \\
0&  3
\end{bmatrix}$$

In [9]:
x = np.array([[1, 0], [0, 3]])
print(x)
x2 = np.linalg.inv(x)
print(x2)

# 역행렬 검증
# 원 행렬과 역행렬을 내적(행렬곱)을 구하면 단위행렬이 나옴
np.dot(x, x2)

[[1 0]
 [0 3]]
[[1.         0.        ]
 [0.         0.33333333]]


array([[1., 0.],
       [0., 1.]])

`6`. 본인의 생년월일로 랜덤시드를 설정하고 표준정규분포에서 1000개의
난수를 생성하라.

``` python
# 생년월일이 21년 07월 06일 이라면 아래와 같이 시드설정
np.random.seed(20210706)
```

In [13]:
np.random.seed(20210706)
x = np.random.randn(1000)

`7`. `6`의 결과로 나온 1000개의 난수중 1.96보다 크거나 -1.96보다 작은
작은값은 모두 몇개인가?

In [16]:
sum([i <= -1.96 or i >= 1.96 for i in x])

42

`8`. 아래와 같은 배열을 선언하라.

In [23]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

차원의 수를 유지하면서 1열을 추출하는 코드를 작성하라. 즉 결과가 아래와
같이 나오도록 하라.

    array([[0],
           [4],
           [8]])

In [29]:
print(a[:,[0]])
print(a[:, 0:1])

[[0]
 [4]
 [8]]
[[0]
 [4]
 [8]]


`9`. 아래의 코드를 관찰하라.

In [30]:
np.random.seed(43052)
a=np.random.randint(low=20,high=25,size=(10,10))

a에서 20,21,22는 각각 몇개씩 있는가?

**note** 공부를 위하여 `np.random.randint()`의 기능을 chatGPT등으로
확인해 볼 것

In [36]:
(a == 20).sum(), (a == 21).sum(), (a == 22).sum()

(17, 20, 19)

`10`. 아래의 코드를 관찰하라.

In [37]:
lst = [[i==j for i in range(5)] for j in range(5)]
lst

[[True, False, False, False, False],
 [False, True, False, False, False],
 [False, False, True, False, False],
 [False, False, False, True, False],
 [False, False, False, False, True]]

lst를 이용하여 shape이 (5,5)인 단위행렬을 만들어라.

In [44]:
# 출력결과는 아래와 같이 나와야 한다.

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [48]:
np.array([[i == j for i in range(5)] for j in range(5)])*1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

`12`. 적당한 코드를 이용하여 아래와 같은 리스트를 생성하라.

In [49]:
lst

[[0, 1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [2, 3, 4, 5, 6],
 [3, 4, 5, 6, 7],
 [4, 5, 6, 7, 8]]

In [51]:
lst = [[i + j for i in range(5)] for j in range(5)]
lst

[[0, 1, 2, 3, 4],
 [1, 2, 3, 4, 5],
 [2, 3, 4, 5, 6],
 [3, 4, 5, 6, 7],
 [4, 5, 6, 7, 8]]

이를 이용하여 아래와 같은 행렬을 선언하라.

In [ ]:
arr

In [52]:
np.array(lst)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

`13`. 적당한 코드를 이용하여 아래와 같은 행렬을 선언하라.

In [53]:
# 출력결과는 아래와 같아야 한다.

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1]])

In [57]:
# 10x10 zero matrix를 생성합니다.
result = np.zeros((10,10))

# 대각선 방향으로 1을 채웁니다.
np.fill_diagonal(result, 1)

# 위와 아래의 대각선 방향으로 1을 채웁니다.
np.fill_diagonal(result[1:], 1)
np.fill_diagonal(result[:, 1:], 1)

print(result)
np.array([[abs(i-j)<2 for i in range(10)] for j in range(10)])*1

[[1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]]


array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1]])

`14`. 성공확률이 45%인 시행을 100번 반복하여 성공하면 True, 실패하면
False를 기록하는 난수열을 생성하라.

**hint:**

In [58]:
np.random.rand() # 0~1사이의 값이 임의로 생성

0.5953173368481477

In [59]:
np.random.rand() < 0.45 # 0~1사이에 랜덤으로 생성된 값이 0.45보다 작다면 True를 리턴

False

In [60]:
np.random.rand(100)<0.45

array([False, False,  True, False, False,  True, False,  True, False,
        True, False, False, False, False,  True,  True,  True, False,
       False, False, False, False,  True,  True,  True,  True, False,
       False,  True,  True, False,  True,  True,  True, False, False,
       False, False,  True, False, False, False, False,  True,  True,
       False, False, False,  True,  True, False,  True, False, False,
        True,  True, False,  True, False, False, False, False, False,
        True, False, False,  True, False, False, False,  True, False,
       False,  True,  True,  True, False, False,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True, False, False,  True,  True, False, False, False,
        True])