# Lesson 06: numpy 공부 3단계 ~ 4단계

최규빈  
2023-07-24

<a href="https://colab.research.google.com/github/guebin/PP2023SUM/blob/main/posts/Day1/02_Numpy/ls07.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" style="text-align: left"></a>

# imports

In [2]:
import numpy as np

# 넘파이 공부 4단계

`-` 목표: 넘파이의 axis를 이해하여 보자.

## np.concatenate

`-` 기본예제

In [3]:
a=np.array([1,2])
b=-a

In [4]:
np.concatenate([a,b])

array([ 1,  2, -1, -2])

`-` 응용

In [5]:
a=np.array([1,2])
b=-a
c=np.array([3,4,5])

In [7]:
np.concatenate([a,b,c])

array([ 1,  2, -1, -2,  3,  4,  5])

-   여기까진 딱히 칸캐터네이트의 메리트가 없어보임
-   리스트였다면 a+b+c 하면 되는 기능이니까?

`-` 2d array에 적용해보자.

In [8]:
a=np.arange(4).reshape(2,2)
b=-a

In [9]:
np.concatenate([a,b])

array([[ 0,  1],
       [ 2,  3],
       [ 0, -1],
       [-2, -3]])

`-` 옆으로 붙일려면?

In [11]:
np.concatenate([a,b],axis=1)

array([[ 0,  1],
       [ 2,  3],
       [ 0, -1],
       [-2, -3]])

`-` 위의 코드에서 axis=1 이 뭐지? axis=0,2 등을 치면 결과가 어떻게 될까?

In [ ]:
np.concatenate([a,b],axis=0)

-   이건 그냥 np.concatenate(\[a,b\])와 같다.
-   np.concatenate(\[a,b\])는 np.concatenate(\[a,b\],axis=0)의
    생략버전이군?

In [ ]:
np.concatenate([a,b],axis=2)

-   이런건 없다.

`-` axis의 의미가 뭔지 궁금함. 좀 더 예제를 살펴보자.

In [12]:
a=np.array(range(2*3*4)).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
b=-a
b

array([[[  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]]])

In [14]:
np.concatenate([a,b],axis=0)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]]])

In [15]:
np.concatenate([a,b],axis=1)

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]]])

In [ ]:
np.concatenate([a,b],axis=2)

-   이번에는 axis=2까지 된다?

In [16]:
np.concatenate([a,b],axis=3)

AxisError: ignored

-   axis=3까지는 안된다?

`-` 뭔가 나름의 방식으로 합쳐지는데 원리가 뭘까?

(분석1) np.concatenate(\[a,b\],axis=0)

In [ ]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [ ]:
a.shape, b.shape, np.concatenate([a,b],axis=0).shape

-   첫번째차원이 바뀌었다 =\> 첫번째 축이 바뀌었다 =\> axis=0 (파이썬은
    0부터 시작하니까!)

(분석2) np.concatenate(\[a,b\],axis=1)

In [17]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [18]:
a.shape, b.shape, np.concatenate([a,b],axis=1).shape

((2, 3, 4), (2, 3, 4), (2, 6, 4))

-   두번째차원이 바뀌었다 =\> 두번째 축이 바뀌었다 =\> axis=1

(분석3) np.concatenate(\[a,b\],axis=2)

In [19]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [ ]:
a.shape, b.shape, np.concatenate([a,b],axis=2).shape

-   세번째차원이 바뀌었다 =\> 세번째 축이 바뀌었다 =\> axis=2

(분석4) np.concatenate(\[a,b\],axis=3)

In [ ]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [ ]:
a.shape, b.shape, np.concatenate([a,b],axis=3).shape

-   네번째차원이 없다 =\> 네번째 축이 없다 =\> axis=3으로 하면 에러가
    난다.

(보너스1)

In [ ]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [ ]:
np.concatenate([a,b],axis=-1)

In [ ]:
a.shape, b.shape, np.concatenate([a,b],axis=-1).shape

-   마지막 차원이 바뀌었다 =\> 마지막 축이 바뀌었다 =\> axis = -1

(보너스2)

In [ ]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [ ]:
np.concatenate([a,b],axis=-2)

In [ ]:
a.shape, b.shape, np.concatenate([a,b],axis=-2).shape

-   마지막에서 2번째 차원이 바뀌었다 =\> 마지막에서 2번째 축이 바뀌었다
    =\> axis = -2

(보너스3)

In [ ]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [ ]:
np.concatenate([a,b],axis=-3)

In [ ]:
a.shape, b.shape, np.concatenate([a,b],axis=-3).shape

-   마지막에서 3번째 차원이 바뀌었다 =\> 마지막에서 3번째 축이 바뀌었다
    =\> axis = -3

(보너스3)

In [ ]:
a=np.array(range(2*3*4)).reshape(2,3,4)
b=-a

In [ ]:
np.concatenate([a,b],axis=-4)

-   마지막에서 4번째 차원은 없다 =\> 마지막에서 4번째 축이 없다 =\> axis
    = -4는 에러가 난다.

`-` 0차원은 축이 없으므로 concatenate를 쓸 수 없다.

In [ ]:
a= np.array(1)
b= np.array(-1)

In [ ]:
a.shape, b.shape

In [ ]:
np.concatenate([a,b])

`-` 꼭 a,b가 같은 차원일 필요는 없다.

In [ ]:
a=np.array(range(4)).reshape(2,2)
b=np.array(range(2)).reshape(2,1)

In [ ]:
np.concatenate([a,b],axis=1)

In [ ]:
a.shape, b.shape, np.concatenate([a,b],axis=1).shape

## np.stack

`-` 혹시 아래가 가능할까?

-   (3,) 결합 (3,) =\> (3,2)

In [ ]:
a=np.array([1,2,3])
b=-a

In [ ]:
a,b

In [ ]:
np.concatenate([a,b],axis=1)

-   불가능

`-` 아래와 같이 하면 해결가능

In [ ]:
a=np.array([1,2,3]).reshape(3,1)
b=-a

In [ ]:
a,b

In [ ]:
np.concatenate([a,b],axis=1)

-   분석: (3) (3) =\> (3,1) (3,1) =\> (3,1) concat (3,1)

`-` 위의 과정을 줄여서 아래와 같이 할 수 있다.

In [ ]:
a=np.array([1,2,3])
b=-a

In [ ]:
np.stack([a,b],axis=1)

`-` 아래도 가능

In [ ]:
np.stack([a,b],axis=0)

`-` 분석해보고 외우자

(분석1)

In [ ]:
a=np.array([1,2,3])
b=-a

In [ ]:
a.shape, b.shape, np.stack([a,b],axis=0).shape

-   1.  1.  =\> 첫 위치에 축을 추가 (axis=0) =\> (1,3) (1,3) =\> (2,3)

(분석2)

In [ ]:
a=np.array([1,2,3])
b=-a

In [ ]:
a.shape, b.shape, np.stack([a,b],axis=1).shape

-   1.  1.  =\> 두 위치에 축을 추가 (axis=1) =\> (3,1) (3,1) =\> (3,2)

`-` 고차원예제

In [ ]:
a=np.arange(3*4*5).reshape(3,4,5)
b=-a

In [ ]:
a.shape, b.shape

In [ ]:
np.stack([a,b],axis=0).shape # (3,4,5) => (1,3,4,5) // 첫 위치에 축이 추가되고 스택

In [ ]:
np.stack([a,b],axis=1).shape # (3,4,5) => (3,1,4,5) // 두번째 위치에 축이 추가되고 스택

In [ ]:
np.stack([a,b],axis=2).shape # (3,4,5) => (3,4,1,5) // 세번째 위치에 축이 추가되고 스택

In [ ]:
np.stack([a,b],axis=3).shape # (3,4,5) => (3,4,5,1) // 네번째 위치에 축이 추가되고 스택

In [ ]:
np.stack([a,b],axis=-1).shape # axis=-1 <=> axis=3

In [ ]:
np.stack([a,b],axis=-2).shape # axis=-2 <=> axis=2

***np.concatenate*** 는 축의 총 갯수를 유지하면서 결합, ***np.stack***은
축의 갯수를 하나 증가시키면서 결합

## sum

`-` 1차원

In [ ]:
a = np.array([1,2,3])
a

In [ ]:
a.sum()

In [ ]:
a.sum(axis=0)

`-` 2차원

In [ ]:
a=np.array(range(6)).reshape(2,3)
a

In [ ]:
a.sum() # 전체합

In [ ]:
a.sum(axis=0)

In [ ]:
a.sum(axis=1)

`-` 2차원 결과 분석

In [ ]:
a.shape, a.sum(axis=0).shape

-   첫번째 축이 삭제됨 =\> axis=0

In [ ]:
a.shape, a.sum(axis=1).shape

-   두번째 축이 삭제됨 =\> axis=1

`-` 연습

In [ ]:
a=np.array(range(10)).reshape(5,2)
a

(문제1) 1열의 합, 2열의 합을 계산하고 싶다면?

(풀이) 차원이 (5,2) =\> (2,) 로 나와야 한다. (그럼 첫번째 축이
삭제되어야 하네?)

In [ ]:
a.sum(axis=0)

(문제2) 1행의 합, 2행의 합, … , 5행의 합을 계산하고 싶다면?

(풀이) 차원이 (5,2) =\> (5,)로 나와야 한다. (그럼 두번째 축이 삭제되어야
하네?)

In [ ]:
a.sum(axis=1)

(문제3) a의 모든원소의 합을 계산하고 싶다면?

(풀이) 차원이 (5,2) =\> () 로 나와야 한다. (첫번째축, 두번째축이 모두
삭제되어야 하네?)

In [ ]:
a.sum(axis=(0,1))

In [ ]:
a.sum() # 즉 a.sum(axis=(0,1))이 디폴트값임

## mean, max, min

`-` 모두 sum이랑 유사한 논리

In [ ]:
a=np.array(range(10)).reshape(5,2)
a

In [ ]:
a.mean(axis=0), a.std(axis=0), a.max(axis=0), a.min(axis=0), a.prod(axis=0)

In [ ]:
a.mean(axis=1), a.std(axis=1), a.max(axis=1), a.min(axis=1), a.prod(axis=1)

## argmax, argmin

`-` 1차원

In [ ]:
a= np.array([1,-2,3,10,4])
a

In [ ]:
a.argmax() # 가장 큰 값이 위치한 원소의 인덱스를 리턴

In [ ]:
a.argmin() # 가장 작은 값이 위치한 원소의 인덱스를 리턴

`-` 2차원

In [ ]:
np.random.seed(43052)
a=np.random.randn(4*5).reshape(4,5)
a

In [ ]:
a.argmin(), a.min()

In [ ]:
a.argmax(), a.max()

In [ ]:
a.argmin(axis=0), a.argmin(axis=1)

In [ ]:
a.argmax(axis=0), a.argmax(axis=1)

## cumsum, cumprod

`-` 1차원

In [ ]:
a=np.array([1,2,3,4])
a

In [ ]:
a.cumsum()

In [ ]:
a.cumprod()

`-` 2차원

In [ ]:
a=np.array(range(3*4)).reshape(3,4)
a

In [ ]:
a.cumsum(axis=0), a.cumsum(axis=1)

In [ ]:
a.cumprod(axis=0), a.cumprod(axis=1)

# Quiz

`1` – `6`. a,b가 아래와 같이 주어졌다고 하자.

In [ ]:
a=np.array([1]*10)
b=np.array([2]*10)

`1`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라.

    array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

`2`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라.

In [ ]:
a=np.array([1]*10)
b=np.array([2]*10)

    array([[1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [1],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2],
           [2]])

`3`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라.

    array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
           [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]

`4`. a,b와 np.concatenate를 이용하여 아래와 같은 배열을 만들어라.

    array([[1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2]])

`5`. a,b와 np.stack을 이용하여 아래와 같은 배열을 만들어라.

    array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
           [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]

`6`. a,b와 np.stack을 이용하여 아래와 같은 배열을 만들어라.

    array([[1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2],
           [1, 2]])

**`7`–`8`**

아래와 같은 매트릭스를 생성하라.

In [ ]:
np.random.seed(43052)
a=np.random.randn(10000).reshape(100,100)
a

`7`. 각 행의 합을 구하라. 즉 1행의 합, 2행의 합, … 100행의 합을
계산하라.

-   1행의합 = 0.38342049 + 1.0841745 + … + 1.18701443

`8`. 각 열의 평균을 구하라. 즉 1열의 평균, 2열의 평균, … , 100열의
평균을 계산하라.