<a href="https://colab.research.google.com/github/simsang1l/python_workshop/blob/main/2023summer/Day1/01_PythonBasicSyntax/ls02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/guebin/PP2023SUM/blob/main/posts/Day1/01_PythonBasicSyntax/ls02.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" style="text-align: left"></a>

# list

## 선언

`-` 리스트의 선언

In [ ]:
a=[11,22]
a

[11, 22]

In [ ]:
type(a)

list

`-` 비어있는 리스트의 선언

In [ ]:
a=[11] # 방법1
a

[11]

In [ ]:
len(a)

1

In [ ]:
a=11

In [ ]:
a=list() # 방법2
a

[]

## 연산

`-` 더하기연산

In [ ]:
a=[11,12]
b=[12,13]

In [ ]:
a

[11, 12]

In [ ]:
b

[12, 13]

In [ ]:
a+b

[11, 12, 12, 13]

- 우리의 예상과 다른 결과가 나옴 $\to$ 파이썬은 R처럼 자체적으로 좋은 계산기능을 내장하고 있지 않음.

`-` 브로드캐스팅과 같이 R에서는 당연히 가능했던 기능을 사용할 수 없음.

In [ ]:
a=[1,2,3]
b=1
a+b

TypeError: can only concatenate list (not "int") to list

`-` 뺄셈은 정의되지 않음

In [ ]:
a=[1,2]
b=[1,2]
a-b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

`-` 곱하기는 정의가능

In [ ]:
a=[1,2]

In [ ]:
2*a # a+a

[1, 2, 1, 2]

`-` 나눗셈은 정의되지 않음

In [ ]:
a=[1,2,1,2]
a/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

`-` 더하기와 곱하기는 원소의 추가와 반복추가를 의미하지만 그렇다고 해서 뺄셈과 나눗셈이 원소의 삭제를 의미하는것은 아님

In [ ]:
a=[1,2,3]
a-[3] # 이런건 없다

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [ ]:
a=[1,2,1,2,1,2]
a/3 # 이런건 없다

TypeError: unsupported operand type(s) for /: 'list' and 'int'

`-` 더하기와 곱하기가 원소의 추가와 반복추가를 의미하여 편리할때도 있긴하지만, 우리는 산술적인 `+`, `*` 를 원하는 경우도 있다. 이럴 경우는 어떻게 할 수 있을까?

(예제)

In [ ]:
a=[1,2]
b=[3,4]

a+b = [4,6] 이 되도록 하려면?

(풀이1)

In [ ]:
a[0]+b[0] # a의 첫번째 원소를 추출, b의 첫번째 원소를 추출, 둘을 더함

4

In [ ]:
a[1]+b[1] # a의 두번째 원소를 추출, b의 두번째 원소를 추출, 둘을 더함

6

In [ ]:
[a[0]+b[0],a[1]+b[1]]

[4, 6]

풀이가 가능한 이유? a,b는 리스트이지만 a[0], a[1], b[0], b[1] 은 각각 인트형임. 인트형은 + 연산이 가능했음.

(풀이2)

numpy 패키지 (파이썬의 여러 수치연산들을 담당하는 라이브러리)

- 이러한 벡터연산은 누구나 필요로 하는 연산임.
- 내가 아니더라도 누군가가 프로그램화 해놓았을 것임.
- 그 누군가가 자신이 만든 코드를 잘 정리하여 무료로 배포했을 수도 있음. (패키지를 배포한다고 표현)
- 그 패키지를 우리는 가져와서 설치한뒤 사용하기만 하면된다.

패키지를 설치하는 방법 (코랩은 이미 설치되어 있음)

- `!pip install numpy` # 최신버전을 설치함
- `!conda install -c conda-forge numpy -y` # 안전한 버전을 설치함

설치된 패키지를 사용하는 방법

- `import numpy` 한뒤에 `numpy.??`로 기능을 사용
- `import numpy as np` 한뒤에 `np.??`로 기능을 사용

In [ ]:
import numpy ## 설치한패키지를 쓰겠다고 선언함

In [ ]:
a=[1,2]
b=[3,4]

In [ ]:
aa=numpy.array(a)
bb=numpy.array(b)
# aa,bb는 리스트가 아니라 넘파이 어레이,
# numpy.array()는 numpy패키지에서 제공하는 array함수를 쓰겠다는 의미.

In [ ]:
aa+bb

array([4, 6])

이런것도 가능

In [ ]:
2*aa

array([2, 4])

In [ ]:
2*aa+1

array([3, 5])

In [ ]:
2*aa+1+bb

array([6, 9])

(풀이3)

In [ ]:
import numpy as np ## 설치한 numpy라는 패키지를 쓰겠음. 그런데 numpy말고 np라는 이름으로 쓰겠음

In [ ]:
np.array(a)

array([1, 2])

In [ ]:
a=[1,2]
b=[3,4]
np.array(a)+np.array(b)

array([4, 6])

## 인덱싱

`-` str형과 동일한 방식

In [ ]:
a=[11,22,33,44,55] # 0 -4 -3 -2 -1

In [ ]:
a[-2:] # 끝의 2개의 원소를 뽑음

[44, 55]

## list 고급

### 리스트는 컨테이너형 객체이다.

`-` 리스트의 원소는 int, float 따위만 가능한 것이 아니다. (리스트는 컨테이너형 객체이므로)

In [ ]:
lst = [1,3.14,True,'a',[1,2],
       (1,2),{'name':'iu','age':27},{1,2,3}]

In [ ]:
lst

[1, 3.14, True, 'a', [1, 2], (1, 2), {'name': 'iu', 'age': 27}, {1, 2, 3}]

각 원소의 타입을 알아보자.

In [ ]:
type(lst[0])

int

In [ ]:
type(lst[1])

float

In [ ]:
type(lst[2])

bool

In [ ]:
type(lst[3])

str

In [ ]:
type(lst[4])

list

In [ ]:
type(lst[5])

tuple

In [ ]:
type(lst[6])

dict

In [ ]:
type(lst[7])

set

`-` str은 컨테이너형이 아니다.

In [ ]:
'abcd'[2]

'c'

- str의 모든 원소는 문자임

### 리스트는 가변형 객체이다.

#### 리스트의 원소 수정

`-` 리스트의 원소를 수정할 수 있다. (리스트는 가변객체이므로)

In [ ]:
a=[11,22,33]
a

[11, 22, 33]

In [ ]:
a[0]

11

In [ ]:
a[0]=111

In [ ]:
a

[111, 22, 33]

`-` 원소수정은 당연한 기능같은데 이것이 불가능한 경우도 있다.

(가능한경우)

In [ ]:
a=['g','u','e','b','i','n']
a

['g', 'u', 'e', 'b', 'i', 'n']

In [ ]:
a[0]

'g'

In [ ]:
a[0]='G'

In [ ]:
a

['G', 'u', 'e', 'b', 'i', 'n']

(불가능한경우)

In [ ]:
a='guebin'
a

'guebin'

In [ ]:
type(a)

str

In [ ]:
a[0]

'g'

In [ ]:
a[0]='G'

TypeError: 'str' object does not support item assignment

#### 리스트의 원소 삭제

(예제)

아래와 같이 문자로 된 리스트를 선언하자.

In [ ]:
a=['g','u','e','b','i','n']
a

['g', 'u', 'e', 'b', 'i', 'n']

사실 더 쉽게 선언할 수 있음

In [ ]:
a= 'guebin' # string으로 a를 선언
a= list(a) # list(a)를 통하여 str을 ㅣist로 변환 -> 그 결과를 a에 다시 저장
a

['g', 'u', 'e', 'b', 'i', 'n']

첫번째 원소를 삭제하고 싶다면?

In [ ]:
del a[0]

In [ ]:
a

['u', 'e', 'b', 'i', 'n']

이 상태에서 다시 첫번쨰 원소를 삭제한다면?

In [ ]:
del a[0]

In [ ]:
a

['e', 'b', 'i', 'n']

#### 리스트의 원소 추가

(예제) 비어있는 리스트를 만들고 원소 0,1,2를 차례로 추가하여 보자.

(풀이1)

In [ ]:
a=[]
a

[]

In [ ]:
a= a + [0]
a

[0]

In [ ]:
a= a + [1]
a

[0, 1]

In [ ]:
a= a + [2]
a

[0, 1, 2]

(풀이2)

In [ ]:
a=[]
a

[]

In [ ]:
a += [0]
a

[0]

In [ ]:
a += [1]
a

[0, 1]

In [ ]:
a += [2]
a

[0, 1, 2]

- 암기법: 중복되는 변수를 지우고 연산자의 순서를 바꾼다.

(풀이3) 리스트 특화기능(=메소드)를 이용

In [ ]:
a=[]
a

[]

In [ ]:
a.append(0)
a

[0]

In [ ]:
a.append(1)
a

[0, 1]

In [ ]:
a.append(2)
a

[0, 1, 2]

`-` `a+[4]`와 `a.append(4)`의 차이점은?

(관찰1)

In [ ]:
a=[1,2,3]
a+[4] ## 리스트 a와 리스트 [4]의 연산결과를 알려줘

[1, 2, 3, 4]

In [ ]:
a ## a는 그대로임. 변화없음

[1, 2, 3]

(관찰2)

In [ ]:
a=[1,2,3]
a.append(4)

In [ ]:
a ## a자체가 변화함

[1, 2, 3, 4]

비슷해보이지만 굉장히 미묘한 차이가 있음

`a.append(4)`: `a`에 4를 append하라 $\to$ `a`가 변함

`a+[4]`: `a`와 4를 연산하라

## list 특수기능

**(append)**

In [ ]:
a=[1,2,3,4]
a.append?

Signature: a.append(object, /)
Docstring: Append object to the end of the list.
Type:      builtin_function_or_method


In [ ]:
a.append(5)
a

[1, 2, 3, 4, 5]

**(clear)**

In [ ]:
a=[1,2,3,4]
a.clear?

Signature: a.clear()
Docstring: Remove all items from list.
Type:      builtin_function_or_method


In [ ]:
a.clear()
a

[]

**(copy)**

In [ ]:
a=[1,2,3,4]
a.copy?

Signature: a.copy()
Docstring: Return a shallow copy of the list.
Type:      builtin_function_or_method


In [ ]:
b=a.copy()
b

[1, 2, 3, 4]

**(count)**

In [ ]:
a=[1,1,2,3,3,4,4,4]
a.count?

Signature: a.count(value, /)
Docstring: Return number of occurrences of value.
Type:      builtin_function_or_method


In [ ]:
a.count(1)

2

In [ ]:
a.count(2)

1

In [ ]:
a.count(3)

2

In [ ]:
a.count(4)

3

**(extend)**

In [ ]:
a=[1,2,3,4]
b=[-1,-2,-3,-4]

In [ ]:
a.extend(b)
a

[1, 2, 3, 4, -1, -2, -3, -4]

In [ ]:
a=[1,2,3,4]
b=[-1,-2,-3,-4]

In [ ]:
a.append(b)

In [ ]:
a

[1, 2, 3, 4, [-1, -2, -3, -4]]

**(index)**

In [ ]:
a=[11,22,'a',True, 22,'a']
a.index?

Signature: a.index(value, start=0, stop=9223372036854775807, /)
Docstring:
Return first index of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method


In [ ]:
a.index(11)

0

In [ ]:
a.index(22)

1

In [ ]:
a.index('a')

2

In [ ]:
a.index(True)

3

**(insert)**

In [ ]:
a=[1,2,3]
a.insert?

Signature: a.insert(index, object, /)
Docstring: Insert object before index.
Type:      builtin_function_or_method


In [ ]:
a.insert(1,88)
a

[1, 88, 2, 3]

**(pop)**

In [ ]:
a=['a',1,2,'d']
a.pop?

Signature: a.pop(index=-1, /)
Docstring:
Remove and return item at index (default last).

Raises IndexError if list is empty or index is out of range.
Type:      builtin_function_or_method


In [ ]:
a.pop() # index=-1 이므로 마지막원소가 나타남

'd'

In [ ]:
a # a는 마지막 원소가 사라진 상태

['a', 1, 2]

In [ ]:
a.pop(0) # index=0 이므로 첫번쨰 원소가 나타남

'a'

In [ ]:
a # a에는 첫번째 원소가 사라진 상태

[1, 2]

**(remove)**

In [ ]:
a=['a',2,3,'d']
a.remove?

Signature: a.remove(value, /)
Docstring:
Remove first occurrence of value.

Raises ValueError if the value is not present.
Type:      builtin_function_or_method


In [ ]:
a.remove('d')

In [ ]:
a

['a', 2, 3]

In [ ]:
a.remove('a')

In [ ]:
a

[2, 3]

**(reverse)**

In [ ]:
a=[1,2,3,4]
a.reverse?

Signature: a.reverse()
Docstring: Reverse *IN PLACE*.
Type:      builtin_function_or_method


In [ ]:
a.reverse()
a

[4, 3, 2, 1]

**(sort)**

In [ ]:
a=[1,3,2,4]
a.sort?

Signature: a.sort(*, key=None, reverse=False)
Docstring:
Sort the list in ascending order and return None.

The sort is in-place (i.e. the list itself is modified) and stable (i.e. the
order of two equal elements is maintained).

If a key function is given, apply it once to each list item and sort them,
ascending or descending, according to their function values.

The reverse flag can be set to sort in descending order.
Type:      builtin_function_or_method


In [ ]:
a.sort()
a

[1, 2, 3, 4]

(다른예제들)

In [ ]:
a=list('guebin')
a

['g', 'u', 'e', 'b', 'i', 'n']

In [ ]:
a.sort()
a

['b', 'e', 'g', 'i', 'n', 'u']

In [ ]:
a.sort(reverse=True)
a

['u', 'n', 'i', 'g', 'e', 'b']

## 중첩 리스트

In [ ]:
A=[[1,2,3],[4,5,6],[7,8,9]]
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
A[0][1]

8

`-` A는 아래와 같은 매트릭스로 이해할 수 있다

$
\bf{A}=\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{bmatrix}
$

`-` A에서 (2,1)의 원소를 뽑고싶다 = 4를 뽑고싶다

In [ ]:
A[1,0]

TypeError: list indices must be integers or slices, not tuple

- 실패

In [ ]:
A[1][0]

4

- 성공

`-` 성공의 이유를 분석해보자.

In [ ]:
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
A[1]

[4, 5, 6]

In [ ]:
A[1][0]

4

`-` 매트릭스는 아니지만 매트릭스 같음!
- 1차원 배열을 다차원 배열로 확장할 수 있는 기본 아이디어를 제공함

## 리스트 컴프리헨션($\star\star\star$)

`-` 리스트 컴프리헨션을 이해하기 전에 for문에 대하여 알아보자.

[예비학습] `for`문 벼락치기

프로그램안에서 반복해서 무엇인가를 하고싶다 $\to$ for

In [ ]:
for i in [0,1,2,3]: ## 반복실행계획
    print(i) ## 반복실행할내용, 탭을이용하여 들여쓰기해야한다.

0
1
2
3


(예제) 1,2,3,4의 합을 for문을 이용하여 구해보자.

In [ ]:
_sum = 0
for i in [1,2,3,4]:
    _sum = _sum + i

In [ ]:
_sum = 0
i=1
_sum = _sum + i ## 1 <= 0+1
i=2
_sum = _sum + i ## 3 <= 1+2
i=3
_sum = _sum + i ## 6 <= 3+3
i=4
_sum = _sum + i ## 10 <= 6+4

In [ ]:
_sum

10

예비학습끝

`-` 예제: $2^0, 2^1, 2^2, 2^3$를 원소로 가지는 리스트를 생성하라.

(풀이1) 직접입력

In [ ]:
x= [2**0, 2**1, 2**2, 2**3]
x

[1, 2, 4, 8]

(풀이2) for문을 이용함

In [ ]:
x=[]
for i in [0,1,2,3]:
    x.append(2**i)

In [ ]:
x

[1, 2, 4, 8]

(풀이3) for문을 이용함

In [ ]:
x=[]
for i in [0,1,2,3]:
    x = x+[2**i]

In [ ]:
x

[1, 2, 4, 8]

(풀이4) for문을 이용함

In [ ]:
x=[]
for i in [0,1,2,3]:
    x += [2**i]

In [ ]:
x

[1, 2, 4, 8]

(풀이5) 리스트컴프리헨션을 이용한 풀이

In [ ]:
x= [2**i for i in [0,1,2,3]]
x

[1, 2, 4, 8]

`-` 리스트컴프리헨션의 문법 암기방법

- 집합에서 조건제시법을 연상
- $\{2^0,2^1,2^2,2^3\}=\{2^i: \text{ for } i = 0,1,2,3 \}$

`-` 리스트컴프리헨션이란?

- 리스트를 매우 효율적으로 만드는 테크닉
- for문에 비하여 가지고 있는 장점: (1) 코드가 간결하다 (2) 빠르다

`-` 예제: 리스트 컴프리헨션을 이용하여 아래와 같은 리스트를 만들어라.

In [ ]:
['SSSS','PPPP','AAAA','MMMM']

['SSSS', 'PPPP', 'AAAA', 'MMMM']

(풀이)

In [ ]:
[i*4 for i in 'SPAM']

['SSSS', 'PPPP', 'AAAA', 'MMMM']

`-` 예제: 리스트컴프리헨션을 이용하여 아래와 같은 리스트를 만들어라.

In [ ]:
['X1','X2','X3','Y1','Y2','Y3']

['X1', 'X2', 'X3', 'Y1', 'Y2', 'Y3']

(풀이)

In [ ]:
[i+j for i in 'XY' for j in '123']

['X1', 'X2', 'X3', 'Y1', 'Y2', 'Y3']

`-` 예제: 리스트컴프리헨션을 이용하여 통계1,...,통계5,수학1,...,수학5를 만들어라.

(풀이)

In [ ]:
[x+y for x in ['stat','math'] for y in '12345']

['stat1',
 'stat2',
 'stat3',
 'stat4',
 'stat5',
 'math1',
 'math2',
 'math3',
 'math4',
 'math5']

- $\{xy : x \in \{{\tt stat},{\tt math}\}, y \in \{1,2,3,4,5\} \}$

(다른풀이) 참고로 for문을 쓰면 좀 복잡해진다.

In [ ]:
_lst = []
for x in ['stat','math']:
    for y in '12345':
        _lst = _lst + [x+y]

In [ ]:
_lst

['stat1',
 'stat2',
 'stat3',
 'stat4',
 'stat5',
 'math1',
 'math2',
 'math3',
 'math4',
 'math5']

`-` 예제: 'jbnu'를 이용하여 아래와 같은 리스트를 만들어라. (리스트컴프리헨션을 이용할것)

In [ ]:
['j','b','n','u']

['j', 'b', 'n', 'u']

(다른풀이) 아래와 같이 풀면 된다는것은 알고 있음  

In [ ]:
list('jbnu')

['j', 'b', 'n', 'u']

(풀이)

In [ ]:
[x for x in 'jbnu']

['j', 'b', 'n', 'u']

`-` 예제: x에는 무엇이 있을까?

(경우1)

In [ ]:
x=1
lst = []
for x in 'jbnu':
    lst = lst + [x]
lst

['j', 'b', 'n', 'u']

In [ ]:
x

'u'

(경우2)

In [ ]:
x=1
lst = [x for x in 'jbnu']
lst

['j', 'b', 'n', 'u']

In [ ]:
x

1

- 진짜 미묘하게 다르죠?

`-` 예제: [X1,X2,X3,...,X100]와 같은 리스트를 만들어보라.

(풀이)

In [ ]:
['X'+str(i) for i in [1,2,3,4]] ## 이걸 4까지가 아니라 100까지 써야함

['X1', 'X2', 'X3', 'X4']

In [ ]:
['X'+str(i) for i in 1:100]

SyntaxError: invalid syntax (<ipython-input-432-4555f37f5468>, line 1)

[예비학습]

In [ ]:
range(0,10)

range(0, 10)

- 이게뭐야?

In [ ]:
_tmp = range(0,10)
_tmp?

Type:        range
String form: range(0, 10)
Length:      10
Docstring:  
range(stop) -> range object
range(start, stop[, step]) -> range object

Return an object that produces a sequence of integers from start (inclusive)
to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
These are exactly the valid indices for a list of 4 elements.
When step is given, it specifies the increment (or decrement).


- 우리가 아는 범위에서는 모르겠음.. 이런게 있나보다 하고 넘어가야 하겠음

In [ ]:
list(range(0,10)) # 0을 포함, 10을 미포함

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- 이게 중요한것임. range(0,10)를 리스트화시키면 [0,1,2,...,9] 와 같은 리스트를 얻을 수 있음.  

In [ ]:
list(range(10)) # 0은 생략가능

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(2,10)) # 2는 포함, 10은 미포함

[2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list(range(1,10,2)) # 2는 포함, 10은 미포함

[1, 3, 5, 7, 9]

예비학습 끝

In [ ]:
['X'+str(i) for i in list(range(1,13))] ## 출력결과가 너무 기니까 101대신에 13으로 변경

['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12']

(아래와 같은 풀이도 가능)

In [ ]:
['X'+str(i) for i in range(1,13)] ## 출력결과가 너무 기니까 101대신에 13으로 변경

['X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'X8', 'X9', 'X10', 'X11', 'X12']

(딴생각) 생각해보니까 for문 뒤에 올 수 있는것이 무엇인지 생각하는것도 흥미로울듯

In [ ]:
for i in '1234':
    print(i)

1
2
3
4


In [ ]:
for i in [1,2,3,4]:
    print(i)

1
2
3
4


In [ ]:
for i in (1,2,3,4): # (1,2,3,4)는 튜플
    print(i)

1
2
3
4


In [ ]:
for i in {1,2,3,4}: # {1,2,3,4}는 set
    print(i)

1
2
3
4


In [ ]:
for i in {'name':'iu','age':28}: #{'name':'iu','age':28} 는 딕셔너리
    print(i)

name
age


In [ ]:
for i in range(1,5):
    print(i)

1
2
3
4


# tuple

## 리스트 vs 튜플

`-` 컨테이너형타입이라는 점, 그리고 연산 및 인덱싱을 하는 방법은 리스트와 같음

- 차이점1: [] 대신에 ()를 사용한다.
- 차이점2: 불변형이다. (원소의 값을 바꿀 수 없음)
- 차이점3: 하나의 원소를 선언할 때는 (1,)와 같이 해야 한다.
- 차이점4: 의미가 명확할때는 튜플의 ()를 생략가능하다.

`-` 컨테이너형이라는 것이 무슨의미?

In [ ]:
a=(4,6,'pencil', 3.2+4.6j, [3,4])

In [ ]:
type(a[2])

str

In [ ]:
type(a[3])

complex

`-` 불변형이라는 것은 무슨의미?

In [ ]:
a[2] = 'Pencil'

TypeError: 'tuple' object does not support item assignment

참고로 a를 튜플이 아니라 리스트로 선언하면 값이 잘 바뀐다.

In [ ]:
a=[4,6,'pencil', 3.2+4.6j, [3,4]]

In [ ]:
a[2]

'pencil'

In [ ]:
a[2]='Pencil'

In [ ]:
a

[4, 6, 'Pencil', (3.2+4.6j), [3, 4]]

`-` 하나의 원소로 이루어진 튜플을 만들때는 쉼표를 붙여야 함.

In [ ]:
[1]+[2,3,4]

[1, 2, 3, 4]

In [ ]:
(1,)+(2,3,4)

(1, 2, 3, 4)

`-` 리스트와 중요한 차이점! 의미가 명확할때 튜플의 괄호는 생략가능하다. (이게 중요합니다)

In [ ]:
a=1,2
a

(1, 2)

의미가 명확할때 생략해야함

In [ ]:
1,2 + 3,4,5

(1, 5, 4, 5)

In [ ]:
(1,2) + (3,4,5)

(1, 2, 3, 4, 5)

## 선언

`-` 소괄호를 이용

In [ ]:
a=(1,2,3)
a

(1, 2, 3)

In [ ]:
type(a)

tuple

`-` 생략가능하다는 점이 포인트

In [ ]:
a=1,2,3
a

(1, 2, 3)

In [ ]:
type(a)

tuple

`-` 원소가 하나인 튜플을 만들고 싶다면?

In [ ]:
a=(1,)
a

(1,)

## 연산

`-` 리스트와 동일

In [ ]:
(1,2)+(3,4,5)

(1, 2, 3, 4, 5)

In [ ]:
(1,2)*2

(1, 2, 1, 2)

## 인덱싱

`-` 리스트와 동일

In [ ]:
a=(1,2,3,-4,-5)
a

(1, 2, 3, -4, -5)

In [ ]:
a[-1]

-5

In [ ]:
a[-3:]

(3, -4, -5)

# Quiz

`1`. 길이가 0인 리스트를 만들어라. (비어있는 리스트를 만들어라)

`2`. 다음의 실행값 중 가장 큰 숫자가 나오는 보기를 골라라. (에러가 나는 코드는 정답에서 제외함)

```Python
(a) len(3.14)
(b) len([3.14])
(c) len('3.14')
```

`3`. 리스트자료형의 `+`와 `*` 연산을 이용하여 아래와 같은 list를 생성하라.

In [ ]:
[1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5]

[1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5]

**hint:** 아래의 코드를 관찰해보세요

In [ ]:
[1]*1+[2]*2

[1, 2, 2]

---

`4`. 아래의 코드를 관찰하고, `sum()`의 기능을 유추하라.

In [ ]:
sum([1,0,1,0])

2

In [ ]:
sum([True,False,True,False])

2

`5`. 다음과 같은 리스트를 고려하자.

In [ ]:
x = [80,60,80,90,55,85,95,100,35,70,75,65,95]
x

[80, 60, 80, 90, 55, 85, 95, 100, 35, 70, 75, 65, 95]

이를 수식으로 표현하면 아래와 같다.

${\bf x} = [x_1,\dots,x_{13}]=[80,60,80,90,55,85,95,100,35,70,75,65,95]$

리스트의 원소중 "$x_i>80$" 의 조건을 만족하는 원소는 모두 몇개인가?

**hint:** 리스트컴프리헨션과 `sum()`함수를 이용할 것

---

`6`. 다음과 같은 리스트를 고려하자.

In [ ]:
['A','B','C','D','A','A','B','A','F','C','C','C','A']

['A', 'B', 'C', 'D', 'A', 'A', 'B', 'A', 'F', 'C', 'C', 'C', 'A']

이 리스트에서 'A' 혹은 'B'의 숫자는 모두 몇개인가?

**hint:** 아래를 관찰

In [ ]:
'A' < 'C'

True

In [ ]:
'B' < 'C'

True

`7`. 아래와 같은 리스트가 있다고 하자.

${\bf x} = [1,2,1,5,6,2,4,7]$

${\bf y} = [3,2,4,1,2,5,6,7]$

이러한 벡터를 파이썬에서 표현하기 위해서 아래와 같은 리스트를 만들었다고 하자.

In [ ]:
x=[1,2,1,5,6,2,4,7]
y=[3,2,4,1,2,5,6,7]

리스트컴프리헨션을 이용하여

$${\bf z}=[x_1^2+y_1^2, \dots, x_{8}^2+y_{8}^2]=[x_i^2+y_i^2: \text{for $i = 1,2,3,\dots,8$}]$$

와 같은 리스트를 생성하라.

`8`. 아래와 같은 문자열이 있다고 하자.

In [ ]:
test_arr = 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAklOUpkDHrfHY17SbrmTIpNLTGK9Tjom/BWDSUGPl+nafzlHDTYW7hdI4yZ5ew18JH4JW9jbhUFrviQzM7xlELEVf4h9lFX5QVkbPppSwg0cda3Pbv7kOdJ/MTyBlWXFCR+HAo3FXRitBqxiX1nKhXpHAZsMciLq8V6RjsNAQwdsdMFvSlVK/7XAt3FaoJoAsncM1Q9x5+3V0Ww68/eIFmb1zuUFljQJKprrX88XypNDvjYNby6vw/Pb0rwert/EnmZ+AW4OZPnTPI89ZPmVMLuayrD2cE86Z/il8b+gw3r3+1nKatmIkjn2so1d01QraTlMqVSsbxNrRFi9wrf+M7Q== schacon@mylaptop.local'

이 문자열에서 대문자의 수를 count하라.

`9`. 리스트컴프리헨션을 이용하여 아래와 같은 리스트를 생성하라.

```
['a',
 'aa',
 'aaa',
 'aaaa',
 'aaaaa',
 'aaaaaa',
 'aaaaaaa',
 'aaaaaaaa',
 'aaaaaaaaa',
 'aaaaaaaaaa'] <- a가 10개있음
```

`10`. 아래와 같은 list가 있다고 하자.

In [ ]:
test_lst = [['g',1],['u',5],['e',2],['b',8],['i',2],['n',9]]

`test_lst`와 리스트컴프리헨션을 이용하여 아래를 출력하는 코드를 구현하라. (2022년 파이썬입문 중간고사 1-(9) 참고)

In [ ]:
['g', 'uuuuu', 'ee', 'bbbbbbbb', 'ii', 'nnnnnnnnn']

['g', 'uuuuu', 'ee', 'bbbbbbbb', 'ii', 'nnnnnnnnn']

`11`. 아래와 같은 list를 생성하라.

```Python
[1,2,2,3,3,3]
```

`12`. 아래와 같은 리스트를 관찰하라.

In [ ]:
lst = ['2022/09/21','2022/10/30','2022/12/25','2023/01/01','2023/01/31','2023/03/20']

이러한 리스트를 아래와 같은 리스트로 변환하는 코드를 작성하라.

In [ ]:
[i.replace('/', '-') for i in lst]

['2022-09-21',
 '2022-10-30',
 '2022-12-25',
 '2023-01-01',
 '2023-01-31',
 '2023-03-20']

In [ ]:
['2022-09-21', '2022-10-30', '2022-12-25', '2023-01-01', '2023-01-31', '2023-03-20']

['2022-09-21',
 '2022-10-30',
 '2022-12-25',
 '2023-01-01',
 '2023-01-31',
 '2023-03-20']

**hint: string의 `.replace()`기능과 리스트 컴프리헨션의 응용**

`13`. 아래와 같은 문자열을 고려하라.

In [ ]:
'2021. 01. 05.'

'2021. 01. 05.'

띄어쓰기를 제거하는 코드를 구현하라. 즉 출력결과가 아래와 같도록 만드는 코드를 구현하라.

In [ ]:
'2021. 01. 05.'[:-1].replace(' ', '')

'2021.01.05'

In [ ]:
'2021.01.05'

'2021.01.05'

**hint**: 아래코드 관찰

In [ ]:
'asdf'.replace('a','')

'sdf'

---

`14`. 아래의 코드를 관찰하라.

In [ ]:
'-'.join(['2022','01','05'])

'2022-01-05'

In [ ]:
'.'.join(['2022','01','05'])

'2022.01.05'

ChatGPT를 이용하여 이 코드가 의미하는 내용을 유추하라.

`15`. 아래와 같이 하나의 특수문자로 이루어진 리스트를 고려하자.

In [ ]:
block = ['■']

이를 이용하여 아래와 같은 결과를 출력하라.

In [ ]:
'-'.join(block*10)

'■-■-■-■-■-■-■-■-■-■'

In [ ]:
'■-■-■-■-■-■-■-■-■-■' # 여기에서 '■'는 모두 10개 있음

'■-■-■-■-■-■-■-■-■-■'

**hint:** join을 이용할 것

`16`. 아래의 실행결과를 되돌리는 코드를 작성하라.

In [ ]:
'2023-03-22'.split('-')

['2023', '03', '22']

즉 아래와 같은 리스트를

In [ ]:
['2023', '03', '22']

['2023', '03', '22']

아래의 string으로 바꾸는 코드를 작성하라.

In [ ]:
'2023-03-22'

'2023-03-22'

**hint:** join을 이용할 것

---

`17`. 길이가 1인 튜플을 만들어 자신의 학번을 저장하라. 길이가 1인 튜플을 만들어 자신의 영문이름을 저장하라. 두 튜플을 + 연산자로 합쳐아래와 같은 출력결과를 얻어라. 최종 결과는 예를들면 아래와 같아야 한다.

In [ ]:
('2021-43052', 'GuebinChoi')

('2021-43052', 'GuebinChoi')

In [ ]:
a = ('2021-43052',)
b = ('GuebinChoi', )
a + b

('2021-43052', 'GuebinChoi')

---

아래는 파이썬프로그래밍 수강생들의 학번, 이름, 출석점수, 과제점수, 중간고사점수, 기말고사점수를 저장한 중첩리스트이다.

In [ ]:
lst = [['2021-43052', 'GuebinChoi', 5, 10, 20, 25],
       ['2019-12342', 'Heung-min Son', 10, 15, 30, 15],
       ['2018-32234', 'hynn', 7, 20, 30, 15],
       ['2022-42323', 'Minji', 8, 20, 20, 35],
       ['2023-55342', 'Hanni', 7, 20, 30, 35],
       ['2022-46624', 'Danielle', 3, 15, 30, 40],
       ['2022-11239', 'Haerin', 10, 20, 30, 40],
       ['2022-32114', 'Hyein', 10, 20, 20, 35]]
lst

[['2021-43052', 'GuebinChoi', 5, 10, 20, 25],
 ['2019-12342', 'Heung-min Son', 10, 15, 30, 15],
 ['2018-32234', 'hynn', 7, 20, 30, 15],
 ['2022-42323', 'Minji', 8, 20, 20, 35],
 ['2023-55342', 'Hanni', 7, 20, 30, 35],
 ['2022-46624', 'Danielle', 3, 15, 30, 40],
 ['2022-11239', 'Haerin', 10, 20, 30, 40],
 ['2022-32114', 'Hyein', 10, 20, 20, 35]]

In [ ]:
# 18
len(lst)

8

In [ ]:
# 19
ll = [lst[i][2] < 7 for i in range(len(lst))]
sum(ll)

2

In [ ]:
# 20
sum([lst[i][2] + lst[i][3] < 21 for i in range(len(lst))])

2

In [ ]:
# 21
[[name, id, *_]for id, name, *_ in lst]

[['GuebinChoi', '2021-43052', 5, 10, 20, 25],
 ['Heung-min Son', '2019-12342', 10, 15, 30, 15],
 ['hynn', '2018-32234', 7, 20, 30, 15],
 ['Minji', '2022-42323', 8, 20, 20, 35],
 ['Hanni', '2023-55342', 7, 20, 30, 35],
 ['Danielle', '2022-46624', 3, 15, 30, 40],
 ['Haerin', '2022-11239', 10, 20, 30, 40],
 ['Hyein', '2022-32114', 10, 20, 20, 35]]

`18`. 파이썬프로그래밍 수강생의 수는 모두 몇명인가?

`19`. 전북대학교 지침에 따라 출석점수가 7보다 작은 학생은 (즉 `출석점수 < 7` 일 경우) F학점을 부여하게 되어있다. 이 기준에 따르면 F를 받는 학생은 모두 몇명인가?

`20`. 파이썬프로그래밍 수업의 경우 `출석+레포트 < 21` 일 경우 F학점을 부여한다고 한다. 이 기준에 따르면 F를 받는 학생은 모두 몇명인가?

`21`. 리스트의 정렬순서를 [학번, 이름, ..., 기말고사점수] 가 아니라 [이름, 학번, ... , 기말고사점수] 와 같이 되도록 변경하는 코드를 작성하라.

(출력예시)

In [ ]:
[[name,studentid,*rest] for studentid, name, *rest in lst]

[['GuebinChoi', '2021-43052', 5, 10, 20, 25],
 ['Heung-min Son', '2019-12342', 10, 15, 30, 15],
 ['hynn', '2018-32234', 7, 20, 30, 15],
 ['Minji', '2022-42323', 8, 20, 20, 35],
 ['Hanni', '2023-55342', 7, 20, 30, 35],
 ['Danielle', '2022-46624', 3, 15, 30, 40],
 ['Haerin', '2022-11239', 10, 20, 30, 40],
 ['Hyein', '2022-32114', 10, 20, 20, 35]]

---

다음은 인터넷에서 긁어온 어떠한 텍스트이다.

In [2]:
text = "국내뿐 아니라 해외 인기도 심상치 않다. 2023년 1월 18일 'Ditto'가 빌보드 핫 100에 96위로 진입했다. 이는 K-pop 역사상 데뷔후 최단 빌보드 Hot 100 차트 입성 기록이다. 다른 뮤지션들이 보통 데뷔 후 수년간 쌓아온 팬덤을 기반으로 빌보드에 입성한데 비해, 뉴진스의 기록은 이례적인 것으로 평가받고 있다. 또한 'OMG'가 빌보드 핫 100에 91위로 진입한 동시에 'Ditto'는 85위로 순위가 상승, 핫 100 주간차트에 두 곡을 올려놓았다. K-Pop 역사상 이 차트에 두 곡 이상을 진입시킨 아티스트는 방탄소년단과 블랙핑크가 유일하다. 'Ditto'는 1월 셋째주 기준, 빌보드뿐만 아니라 영국 오피셜 싱글 차트 '톱 100'에 2주 연속 진입하기도 했다."

In [5]:
# 22
len(text.split('. '))

7

In [14]:
# 23
[len(i.split(' ')) for i in text.replace('. ', '.').split('.')]

[6, 9, 11, 18, 18, 12, 16, 1]

In [16]:
# 24
sum(['100' in i for i in text.replace('. ', '.').split('.')])

4

`22`. text는 총 몇개의 문장으로 이루어져 있는가?

**hint:** 이 텍스트의 문장은 모두 `.`로 끝난다.

`23`. 각 문장은 몇개의 단어로 이루어져 있는가?

**hint:** 각 단어는 공백으로 구분된다.

`24`. `100`이라는 단어가 포함된 문장은 모두 몇 개 인가?

**hint:** 아래의 코드를 관찰

In [ ]:
'a' in 'abcd'

True